### ISSUE TITLE
Is it really as straightforward as regex and replace?

### ISSUE THREAD

**Issue by edasque** [containous/plugin-rewritebody#6]
Hi,

I am trying to do in Traefik2 what others are doing with Nginx like so:
```
    sub_filter_types application/javascript;
    sub_filter '"http://"+localip' 'window.location.origin';
```

So after configuring the plugin (v0.2.2), I have defined the middleware in YAML like so:
```
  middlewares:
    rewrite-site-js:
      plugin:
        rewritebody:
          lastModified: true
          rewrites:
            - regex: '"http://"+localip'
            - replacement: "window.location.origin"
```

Strangely this causes the whole home page for that service to look something like:
```
window.location.originwindow.location.origin window.location.originwindow.location.origin window.location.origin window.location.originwindow.location.origin
```
which seems singular. Is something in my regexp getting interpreted in odd ways? I've tried to escape it to no avail.
